use super::Card;
use super::Rank;
use super::Suit;

#[rustfmt::skip]
const CARDS: [Card; 52] = [
    Card { suit: Suit::Clubs, rank: Rank::One },
    Card { suit: Suit::Clubs, rank: Rank::Two },
    Card { suit: Suit::Clubs, rank: Rank::Three },
    Card { suit: Suit::Clubs, rank: Rank::Four },
    Card { suit: Suit::Clubs, rank: Rank::Five },
    Card { suit: Suit::Clubs, rank: Rank::Six },
    Card { suit: Suit::Clubs, rank: Rank::Seven },
    Card { suit: Suit::Clubs, rank: Rank::Eight },
    Card { suit: Suit::Clubs, rank: Rank::Nine },
    Card { suit: Suit::Clubs, rank: Rank::Ten },
    Card { suit: Suit::Clubs, rank: Rank::Jack },
    Card { suit: Suit::Clubs, rank: Rank::Queen },
    Card { suit: Suit::Clubs, rank: Rank::King },

    Card { suit: Suit::Diamonds, rank: Rank::One },
    Card { suit: Suit::Diamonds, rank: Rank::Two },
    Card { suit: Suit::Diamonds, rank: Rank::Three },
    Card { suit: Suit::Diamonds, rank: Rank::Four },
    Card { suit: Suit::Diamonds, rank: Rank::Five },
    Card { suit: Suit::Diamonds, rank: Rank::Six },
    Card { suit: Suit::Diamonds, rank: Rank::Seven },
    Card { suit: Suit::Diamonds, rank: Rank::Eight },
    Card { suit: Suit::Diamonds, rank: Rank::Nine },
    Card { suit: Suit::Diamonds, rank: Rank::Ten },
    Card { suit: Suit::Diamonds, rank: Rank::Jack },
    Card { suit: Suit::Diamonds, rank: Rank::Queen },
    Card { suit: Suit::Diamonds, rank: Rank::King },

    Card { suit: Suit::Hearts, rank: Rank::One },
    Card { suit: Suit::Hearts, rank: Rank::Two },
    Card { suit: Suit::Hearts, rank: Rank::Three },
    Card { suit: Suit::Hearts, rank: Rank::Four },
    Card { suit: Suit::Hearts, rank: Rank::Five },
    Card { suit: Suit::Hearts, rank: Rank::Six },
    Card { suit: Suit::Hearts, rank: Rank::Seven },
    Card { suit: Suit::Hearts, rank: Rank::Eight },
    Card { suit: Suit::Hearts, rank: Rank::Nine },
    Card { suit: Suit::Hearts, rank: Rank::Ten },
    Card { suit: Suit::Hearts, rank: Rank::Jack },
    Card { suit: Suit::Hearts, rank: Rank::Queen },
    Card { suit: Suit::Hearts, rank: Rank::King },

    Card { suit: Suit::Spades, rank: Rank::One },
    Card { suit: Suit::Spades, rank: Rank::Two },
    Card { suit: Suit::Spades, rank: Rank::Three },
    Card { suit: Suit::Spades, rank: Rank::Four },
    Card { suit: Suit::Spades, rank: Rank::Five },
    Card { suit: Suit::Spades, rank: Rank::Six },
    Card { suit: Suit::Spades, rank: Rank::Seven },
    Card { suit: Suit::Spades, rank: Rank::Eight },
    Card { suit: Suit::Spades, rank: Rank::Nine },
    Card { suit: Suit::Spades, rank: Rank::Ten },
    Card { suit: Suit::Spades, rank: Rank::Jack },
    Card { suit: Suit::Spades, rank: Rank::Queen },
    Card { suit: Suit::Spades, rank: Rank::King },
];
